package exceptionHandling;

public class exception2 {

	public static void main(String[] args) {
		try {
			int[] num= {1,2,3,4,5};
			System.out.println(num[6]);
		}
        catch(Exception e){
        	System.out.println("divya");
        }
	}

}
